paths:
  data_dir: data
  base_file: data/base.xlsx
  input_dir: data/input
  output_dir: data/output
  logs_dir: data/logs
  lookup_product: data/lookups/product.xlsx
  columns_registry: data/columns_registry.xlsx
mappings:
  core: mappings/columns_core.yaml
  aliases:
    OZ: mappings/columns_aliases_OZ.yaml
    WB: mappings/columns_aliases_WB.yaml
    YM: mappings/columns_aliases_YM.yaml
processing:
  enable_parquet: true
  default_platforms: [OZ, WB, YM]
  id_column: id_key
